### ISSUE TITLE
Settings aren't applied

### ISSUE THREAD

**Issue by marc-eggers** [artumino/NomaiVR-FixedFoveatedRendering#1]
First of all artumino, thanks for making this! It's a great plugin to squeeze some much needed performance out of NomaiVR.

The issue I'm having is that the settings are completely broken for me. The only setting that actually works is toggling FFR on/off. The rest, even when edited in the config file, don't do anything at all. None of the radius or shading rate changes affect the image whatsoever, neither did turning on debug mode.

Also, trying to update numeric values in the config via the virtual keyboard doesn't work. When hitting "done" after entering the number, nothing in the input field actually changes. That might be an issue with NomaiVR though.

What I've tried to solve this issue:
- changed default-config.json values (maybe those were used?)
- ran both OWML as well as the game as an administrator
- lots of reinstalling, restarting the game etc.
- installing the mod into OWML manually
- downloading release 1.0.1, changing default-config.json values to desired ones, then manually installing

None of this worked. If there is some easy fix I am missing here, I'd really appreciate it if you could let me know, and maybe add a readme to help others avoid this issue in future. Let me know if there's any other info that might be of use here.

My setup:
- Valve Index, SteamVR
- Steam copy of OW
- OWML, NomaiVR, FFR, and the game all updated to latest versions (as of posting this issue)

Have a nice weekend!

**Comment by artumino** [comment]
Hi there, the new release should update the settings properly now.
The virtual keyboard not writing values is a NomaiVR bug which I'll probably take a look at in the next few days, for now manually changing the "config.json" to change the radius of the regions should work fine.

**Comment by marc-eggers** [comment]
Can confirm, it's all working now. Thank you!
